name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@master
    - name: Build Project
      run:  xcodebuild clean test -project SampleiOSApp/SampleiOSApp.xcodeproj -scheme SampleiOSApp -destination "platform=iOS Simulator,name=iPhone 11 Pro"

