name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Clean Build
      run:  xcodebuild clean -project SampleiOSApp/SampleiOSApp.xcodeproj
    - name: Build Project
      run: xcodebuild build -project SampleiOSApp/SampleiOSApp.xcodeproj
